### ISSUE TITLE
Issue when using examples that require signature like AccountBalanceCacheExample or OrdersExample

### ISSUE THREAD

**Issue by fromjgor** [joaopsilva/binance-java-api#1]
Hello João,

thank you for providing API for binance.com.
It is working fine unless the signature is required.

I am raising an issue when run your examples such as AccountBalanceCacheExample or OrdersExample even if API and secret keys are provided.

I am getting the following error message:
Exception in thread "main" com.binance.api.client.exception.BinanceApiException: Signature for this request is not valid.
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:139)
	at com.binance.api.client.impl.BinanceApiRestClientImpl.getAccount(BinanceApiRestClientImpl.java:144)
	at com.binance.api.examples.AccountBalanceCacheExample.initializeAssetBalanceCacheAndStreamSession(AccountBalanceCacheExample.java:45)
	at com.binance.api.examples.AccountBalanceCacheExample.<init>(AccountBalanceCacheExample.java:34)
	at com.binance.api.examples.AccountBalanceCacheExample.main(AccountBalanceCacheExample.java:80)

Maybe it is about how the signature is built or the latest changes in the API of binance (even if couldn't find anything there)

How it could be fixed?

Thanks again and 
Best Regards, jgor

**Comment by joaopsilva** [comment]
Hi there @fromgor ,

Could you please double-check the secret? I can only reproduce your problem if I use a wrong secret (not API-key).

Best regards,
João

**Comment by fromjgor** [comment]
Hi João,

thank you a lot. 
Of course I was using the wrong secret.
The issue has been resolved.

Ciao, Jgor

**Comment by joaopsilva** [comment]
Great, also, make sure to fork https://github.com/binance-exchange/binance-java-api instead, since that is now the official repo for the Java API.
