### ISSUE TITLE
SunCertPathBuilderException unable to find valid certification

### ISSUE THREAD

**Issue by MilanNz** [joaopsilva/binance-java-api#3]
Hello, thank you for great api but i have problem with following issue: 

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)

Do you have any idea how to solve this issue?

**Comment by VaultDeveloper** [comment]
I think this repo will not have upgrades, you need to declare the error in binance-exchange's fork : https://github.com/binance-exchange/binance-java-api

I declare more or less the same issue : https://github.com/binance-exchange/binance-java-api/issues/20

**Comment by MilanNz** [comment]
cool, thanks :)

Edit:
I've solved this issue using [InstallCert](https://github.com/escline/InstallCert/blob/master/InstallCert.java) class.

**Comment by Micha1990** [comment]
Which host and port did you use with InstallCert? Do I just have to run it or integrate it in the program somehow?

**Comment by venuchitta** [comment]
You can use host api.binance.com with no port like "java InstallCert api.binance.com". Then follow instructions as per http://www.mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/
